name: Issue template
description: Issueを作成する際に利用ください
title: "[Issue]: "
labels: ["issue"]
projects: ["system-data-infra/6"]
body:
  - type: markdown
    attributes:
      value: |
        Issueの作成ありがとうございます。
  - type: markdown
    id: issue-reason
    attributes:
      label: Issue作成の背景
      description: こちらに`Issue`を作成した背景（理由）を記載ください。
      placeholder: こちらに`Issue`を作成した背景（理由）を記載ください。
    validations:
      required: true

  - type: markdown
    id: issue
    attributes:
      label: Issueの内容
      description: こちらに`Issue`の内容を記載ください。
      placeholder: こちらに`Issue`の内容を記載ください。
    validations:
      required: true

  - type: markdown
    id: issue
    attributes:
      label: Issueの完了条件（終了条件）
      description: こちらに`Issue`の完了（終了）する条件をチェックボックス形式で記載ください。
      placeholder: こちらに`Issue`の完了（終了）する条件をチェックボックス形式で記載ください。
    validations:
      required: true
