name: Issue template
description: Issueを作成する際に利用ください
title: "[Issue]: "
labels: ["issue"]
projects: ["system-data-infra/6"]
body:
  - type: markdown
    attributes:
      value: |
        Issueの作成ありがとうございます。

  - type: textarea
    id: issue-reason
    attributes:
      label: Issue 作成の背景
      description: こちらに`Issue`を作成した背景（理由）を記載ください。(なるべく短文で箇条書きで、図とかもあれば記載してください)
      value: |
        - 箇条書き1
        - 箇条書き2
        - 箇条書き3
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue の内容
      description: こちらに`Issue`の内容を記載ください。(なるべく短文で箇条書きで)
      value: |
        - 箇条書き1 
        - 箇条書き2
        - 箇条書き3
    validations:
      required: true

  - type: textarea
    id: issue-close-conditions
    attributes:
      label: Issue の完了条件（終了条件）
      description: こちらに`Issue`の完了（終了）する条件をチェックボックス形式で記載ください。
      value: |
        -[] チェックボックス1 
        -[] チェックボックス2
        -[] チェックボックス3
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: Issue に関連する task
      description: こちらに`Issue`に関連する`task`チェックボックス形式で作成してください。あとで追加しても問題ないです。) 
      placeholder: こちらに`Issue`に関連する`task`チェックボックス形式で作成してください。あとで追加しても問題ないです。) 
      value: |
        - URL
        - URL
        - URL
