name: Story template
description: Storyを作成する際に利用ください
title: "[Story]: "
labels: ["story"]
projects: ["system-data-infra/6"]
body:
  - type: markdown
    attributes:
      value: |
        Storyの作成ありがとうございます。

  - type: textarea
    id: Story-reason
    attributes:
      label: Story 作成の背景
      description: こちらに`Story`を作成した背景（理由）を記載ください。
      placeholder: こちらに`Story`を作成した背景（理由）を記載ください。
    validations:
      required: true

  - type: textarea
    id: Story
    attributes:
      label: Story の内容
      description: こちらに`Story`の内容を記載ください。
      placeholder: こちらに`Story`の内容を記載ください。
    validations:
      required: true

  - type: textarea
    id: Story-close-conditions
    attributes:
      label: Story の完了条件（終了条件）
      description: こちらに`Story`の完了（終了）する条件をチェックボックス形式で記載ください。
      placeholder: こちらに`Story`の完了（終了）する条件をチェックボックス形式で記載ください。
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: Story に関連する task
      description: こちらに`Story`に関連する`task`チェックボックス形式で作成してください。あとで追加しても問題ないです。) 
      placeholder: こちらに`Story`に関連する`task`チェックボックス形式で作成してください。あとで追加しても問題ないです。) 
