name: Sub Story template
description: Sub Storyを作成する際に利用ください
title: "[Sub Story]: "
labels: ["sub story"]
projects: ["system-data-infra/6"]
body:
  - type: markdown
    attributes:
      value: |
        Sub Storyの作成ありがとうございます。

  - type: textarea
    id: Story
    attributes:
      label: 関連する Story を記載してください。
      description: こちらに関連する`Story`を記載してください。
      placeholder: こちらに関連する`Story`を記載してください。
    validations:
      required: true

  - type: textarea
    id: Sub-Story-reason
    attributes:
      label: Sub Story 作成の背景
      description: こちらに`Sub Story`を作成した背景（理由）を記載ください。
      placeholder: こちらに`Sub Story`を作成した背景（理由）を記載ください。
    validations:
      required: true

  - type: textarea
    id: Sub-Story
    attributes:
      label: Sub Story の内容
      description: こちらに`Sub Story`の内容を記載ください。
      placeholder: こちらに`Sub Story`の内容を記載ください。
    validations:
      required: true

  - type: textarea
    id: Sub-Story-close-conditions
    attributes:
      label: Sub Story の完了条件（終了条件）
      description: こちらに`Sub Story`の完了（終了）する条件をチェックボックス形式で記載ください。
      placeholder: こちらに`Sub Story`の完了（終了）する条件をチェックボックス形式で記載ください。
    validations:
      required: true
  
  - type: textarea
    id: task
    attributes:
      label: Sub Story に関連する task
      description: こちらに`Sub Story`に関連する`task`チェックボックス形式で作成してください。(あとで追加しても問題ないです。) 
      placeholder: こちらに`Sub Story`に関連する`task`チェックボックス形式で作成してください。(あとで追加しても問題ないです。) 
