name: task template
description: taskを作成する際に利用ください
title: "[task]: "
labels: ["task"]
projects: ["system-data-infra/6"]
body:
  - type: markdown
    attributes:
      value: |
        taskの作成ありがとうございます。

  - type: textarea
    id: issue-or-sub-issue
    attributes:
      label: 関連する Issueや`Story`やチーム目標を記載してください
      description: こちらに関連する`Issue`を記載してください。
      value: |
        - [ ] URL
        - [ ] URL
        - [ ] URL
    validations:
      required: true

  - type: textarea
    id: task-reason
    attributes:
      label: task 作成の背景
      description: こちらに`task`を作成した背景（理由）を記載ください。(なるべく短文で箇条書きで)
      value: |
        - 箇条書き1 
        - 箇条書き2
        - 箇条書き3
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: task の内容
      description: こちらに`task`の内容を記載ください。(なるべく短文で箇条書きで)
      value: |
        - 箇条書き1 
        - 箇条書き2
        - 箇条書き3
    validations:
      required: true

  - type: textarea
    id: task-close-conditions
    attributes:
      label: task の完了条件（終了条件）
      description: こちらに`task`の完了（終了）する条件をチェックボックス形式で記載ください。
      value: |
        - [ ] チェックボックス1
        - [ ] チェックボックス2
        - [ ] チェックボックス3
    validations:
      required: true
